version: 2

registries:
  coverlet-azure-devops:
    type: nuget-feed
    url: https://pkgs.dev.azure.com/tonerdo/coverlet/_packaging/coverlet-nightly/nuget/v3/index.json

updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 20
    registries:
      - coverlet-azure-devops
    labels:
      - "type: dependencies"
      - ".NET"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
